version: '3.2'
# (proxy) + (react) + (express) + (mysql + adminer)

services:
  # DB - MYSQL server
  db_mysql:
    container_name: 'db_mysql'
#    cap_add:
#      - SYS_NICE
    build:
      dockerfile: 'Dockerfile'
      context: 'db_mysql'
    volumes:
      - "./db_mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
#      - './db_mysql/.mysql-data/db:/var/lib/mysql'
#    command: '--default-authentication-plugin=mysql_native_password --sql_mode=""'
    hostname: 'localhost'
    ports:
      - '9906:3306'
    env_file:
      - 'db_mysql/.env'
#    environment:
#      <<: *common-variables
    restart: 'always'

  # DB - ADMINER client
  db_adminer:
    container_name: 'db_adminer'
    depends_on:
      - 'db_mysql'
    build:
      dockerfile: 'Dockerfile'
      context: 'db_adminer'
    hostname: 'localhost'
    ports:
      - '8000:8080'
    env_file:
      - 'db_adminer/.env'
    restart: 'unless-stopped'

  # UI - REACT JS client
  ui_react:
    container_name: 'ui_react'
    build:
      dockerfile: 'Dockerfile'
      context: 'ui_react'
    volumes:
      - '/app/node_modules'
      - './ui_react:/app'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - '3005:3005'
    env_file:
      - 'ui_react/.env'
    tty: true
    stdin_open: true
#    command: 'bash -c "yarn && yarn dev"'
    restart: 'always'

  # API - EXPRESS JS server
  api_express:
    container_name: 'api_express'
    depends_on:
      - 'db_mysql'
    build:
      dockerfile: 'Dockerfile'
      context: 'api_express'
    volumes:
      - '/app/node_modules'
      - './api_express:/app'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - '4005:4005'
    env_file:
      - 'api_express/.env'
#    environment:
#      <<: *common-variables
    tty: true
    #    command: 'bash -c "while !</dev/tcp/localhost/3306; do sleep 1; done; yarn && yarn dev"'
#    command: 'bash -c "yarn && yarn dev"'
    restart: 'always'

  # PROXY - NGINX server
  proxy_nginx:
    container_name: 'proxy_nginx'
#    network_mode: 'host'
    depends_on:
      - 'api_express'
      - 'ui_react'
    build:
      dockerfile: 'Dockerfile'
      context: 'proxy_nginx'
    ports:
      - "3050:80"
    env_file:
      - 'proxy_nginx/.env'
    restart: 'always'
