version: '3.2'

services:
  # DB - MYSQL server
  db_mysql:
    container_name: 'db_mysql'
    build:
      dockerfile: 'Dockerfile'
      context: '.'
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    hostname: 'localhost'
    env_file:
      - '.env'
    ports:
      - ${VIRTUAL_DB_PORT}:${VIRTUAL_DB_PORT}
    restart: 'always'
