version: '3.2'
services:

  # API service BACKend --> puerto 4005(pc):4000(docker)
  api_service_b:
    container_name: 'api_service_b'
    env_file:
      - './.env'
    image: 'node:14'
    volumes:
      - '.:/var/www/html'
    working_dir: '/var/www/html/'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    ports:
      - '4005:4005'
    tty: true
    command: 'bash -c "yarn && yarn dev"'
  #    restart: 'always'
