version: '3.2'

networks:
  db_mysql_custom-net:
    external: true

services:
  # WEB service FRONTend --> puerto 3005(pc):3005(docker)
  ui_react:
    networks:
      - db_mysql_custom-net
    container_name: 'ui_react'
    image: 'node:14'
    volumes:
      - '.:/var/www/html'
    working_dir: '/var/www/html/'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    ports:
      - '3005:3005'
    env_file:
      - './.env'
    tty: true
    command: 'bash -c "yarn && yarn dev"'
#    restart: 'always'
